Sismedica/urls.py
from django.contrib import admin
from django.urls import path,include
from apps.clinica.views import Inicio
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
from apps.usuarios.views import  Login, LogoutUsuario

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/',include(('apps.usuarios.urls','usuarios'))),
    path('clinica/',include(('apps.clinica.urls','clinica'))),
    path('',login_required(Inicio.as_view()), name = 'index'),
    path('accounts/login/',Login.as_view(),name='login'),
    path('logout/',login_required(LogoutUsuario),name='logout'),
]

apps/clinica/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

"""Asignacion de la rutas de la aplicacion
"""

urlpatterns =[
    path('crear_expediente/', login_required(CrearExpediente.as_view()) ,name= 'crear_expediente'),
    path('listar_expediente/',login_required(ListadoExpediente.as_view()),name='listar_expediente'),
    path('editar_expediente/<pk>',login_required(ActualizarExpediente.as_view()), name = 'editar_expediente'),


    path('crear_paciente/', login_required(CrearPaciente.as_view()),name= 'crear_paciente'),
    path('listar_paciente/',login_required(ListadoPaciente.as_view()),name='listar_paciente'),
    path('editar_paciente/<int:pk>',login_required(ActualizarPaciente.as_view()), name = 'editar_paciente'),
    path('eliminar_paciente/<int:pk>',login_required(EliminarPaciente.as_view()),name='eliminar_paciente'),

    path('crear_consulta/', login_required(CrearConsulta.as_view()),name='crear_consulta'),
    path('listar_consulta/',login_required(ListadoConsulta.as_view()),name='listar_consulta'),
    path('editar_consulta/<int:pk>',login_required(ActualizarConsulta.as_view()),name='editar_consulta'),
    path('eliminar_consulta/<int:pk>',login_required(EliminarConsulta.as_view()),name='eliminar_consulta'),


    path('crear_cita/',login_required(CrearCita.as_view()),name='crear_cita'),
    path('listar_cita/',login_required(ListadoCita.as_view()),name='listar_cita'),
    path('editar_cita/<pk>',login_required(ActualizarCita.as_view()), name = 'editar_cita'),
    path('eliminar_cita/<pk>',login_required(EliminarCita.as_view()),name='eliminar_cita'),

    path('crear_incapacidad/',login_required(CrearIncapacidad.as_view()),name= 'crear_incapacidad'),
    path('listar_incapacidad/',login_required(ListadoIncapacidad.as_view()),name='listar_incapacidad'),
    path('eliminar_incapacidad/<pk>',login_required(EliminarIncapacidad.as_view()),name='eliminar_incapacidad'),

    path('crear_medico/', login_required(CrearMedico.as_view()) ,name= 'crear_medico'),
    path('listar_medico/',login_required(ListadoMedicos.as_view()),name='listar_medico'),
    path('editar_medico/<int:pk>',login_required(ActualizarMedico.as_view()), name = 'editar_medico'),
    path('eliminar_medico/<int:pk>',login_required(EliminarMedico.as_view()),name='eliminar_medico'),  

    path('crear_especialidad/', login_required(CrearEspecialidad.as_view()) ,name= 'crear_especialidad'),
    path('listar_especialidad/',login_required(ListadoEspecialidad.as_view()),name='listar_especialidad'),
    path('eliminar_especialidad/<pk>',login_required(EliminarEspecialidad.as_view()),name='eliminar_especialidad'),
      
]

apps/clinica/models.py
from django.db import models

# Create your models here.

class Expediente(models.Model):
    idExpediente = models.AutoField(primary_key=True)
    nombreCompleto = models.CharField('Nombres', max_length= 200,null=True, blank=True)
    edad =models.IntegerField('Edad',null=True,blank=True)
    sexo = models.CharField('Sexo',max_length= 200,null=True, blank=True)
    estado = models.CharField('Estado',max_length= 200,null=True, blank=True)
    altura = models.FloatField('Altura',null=True, blank=True)
    peso = models.FloatField('Peso',null=True, blank=True)
    temperatura = models.FloatField('Temperatura',null=True, blank=True)
    presart = models.CharField('Presión Arterial',max_length= 200,null=True, blank=True)
    enfermedadeshe = models.TextField('Enfermedades Hereditarias',max_length= 400,null=True, blank=True)
    alergias = models.TextField('Alergias',max_length= 400,null=True, blank=True)
    obserpsi = models.TextField('Observaciones Psicologicas',max_length= 400,null=True, blank=True)

    class Meta:
        verbose_name = 'Expediente'
        verbose_name_plural = 'Expedientes'
        ordering =['idExpediente']
    def __str__(self):
        st = str(self.idExpediente) +' '+str(self.nombreCompleto)
        return st
        

class Paciente(models.Model):

    id_paciente = models.AutoField(primary_key=True)
    idExpediente = models.ForeignKey(Expediente, null=True, on_delete=models.SET_NULL)
    nombre = models.CharField('Nombre',max_length=100, blank=False, null=False)
    apellidos = models.CharField('Apellidos', max_length=100, blank=False, null=False)
    dui = models.CharField('DUI', max_length=10, blank=False,null=False)
    sexo = models.CharField('Sexo', max_length=10, blank=False, null=False)
    email = models.CharField('email',max_length=100,blank=False, null=False)
    estadoCivil = models.CharField('estadoCivil', max_length=10, blank=False,null=False)
    telefono = models.CharField('Telefono', max_length=9, blank=False,null=False)
    fechaNaci = models.DateField('Fecha de Nacimiento',blank=False,null=False)
    direccion = models.TextField('Direccion',max_length=300, blank=False,null=False)
    departamento = models.CharField('Departamento',max_length=100,blank=False,null=False)
    municipio = models.CharField('Municipio',max_length=100,blank=False,null=False)
    altura = models.FloatField('Altura',blank=False,null=False)
    peso = models.FloatField('Peso', blank=False,null=False)
    
    class Meta:
            verbose_name = 'Paciente'
            verbose_name_plural = 'Pacientes'
            ordering = ['id_paciente']

    def __str__(self):
        return self.nombre + ' ' + self.apellidos

class Medico(models.Model):
    idMedico= models.AutoField(primary_key=True)
    nombre = models.CharField('Nombre',max_length=100, blank=False, null=False)
    apellidos = models.CharField('Apellidos', max_length=100, blank=False, null=False)
    dui = models.CharField('DUI', max_length=10, blank=False,null=False)
    sexo = models.CharField('Sexo', max_length=1, blank=False, null=False)
    email = models.CharField('email',max_length=100,blank=False, null=False)
    estadoCivil = models.CharField('estadoCivil', max_length=10, blank=False,null=False)
    telefono = models.CharField('Telefono', max_length=9 ,blank=False,null=False)
    fechaNaci = models.DateField('Fecha de Nacimiento',blank=False,null=False)
    direccion = models.TextField('Direccion',max_length=300, blank=False,null=False)
    departamento = models.CharField('Departamento',max_length=100,blank=False,null=False)
    municipio = models.CharField('Municipio',max_length=100,blank=False,null=False)
    altura = models.IntegerField('Altura',blank=False,null=False)
    peso = models.IntegerField('Peso', blank=False,null=False)

    class Meta:
        verbose_name='Medico'
        verbose_name_plural= 'Medicos'
        ordering=['idMedico']
    
    def __str__(self):
        return self.nombre + ' ' + self.apellidos

class Referencia (models.Model):
    idReferencia = models.AutoField(primary_key =True)
    idMedico = models.IntegerField('IdMedico', blank=False,null=False)
    nombre= models.CharField('Nombre', max_length=50, blank=False, null=False)
    cargo = models.CharField('Cargo', max_length=50, blank=False, null=False)
    telefono = models.CharField('Telefono', max_length=50, blank=False, null=False)
    lugarReferencia = models.CharField('LugarReferencia', max_length=50,blank=False,null=False)
    tipoReferencia = models.CharField('TipoReferencia', max_length=50, blank=False, null=False)

    class Meta:
            verbose_name='Referencia'
            verbose_name_plural= 'Referencias'
            ordering=['idReferencia']
    
    def __str__(self):
        return self.nombre + ' ' + self.lugarReferencia

class Cita (models.Model):
    idCita= models.AutoField(primary_key=True)
    idMedico = models.IntegerField('IdMedico', blank=False,null=False)
    idPaciente = models.IntegerField('IdPaciente', blank=False, null=False)
    idEspecialidad = models.IntegerField('IdEspecialidad',blank = False, null= False)
    fecha = models.DateField('Fecha',blank= False, null=False)
    hora = models.CharField('Hora', max_length=5, blank=False, null=True)

    class Meta:
        verbose_name='Cita'
        verbose_name_plural='Citas'
        ordering=['idCita']

    def __str__(self):
        st = str(self.idCita)
        return st

class Especialidad(models.Model):
    idEspecialidad = models.AutoField(primary_key=True)
    nombre = models.CharField('Nombre', max_length=40, blank =False, null=False)

    class Meta: 
        verbose_name = 'Especialidad'
        verbose_name_plural = 'Especialidades'
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

class Consulta (models.Model):
    idConsulta = models.AutoField(primary_key=True)
    idMedico = models.ForeignKey(Medico, null=True, on_delete=models.SET_NULL)
    idPaciente = models.ForeignKey(Paciente, null=True, on_delete=models.SET_NULL)
    idEspecialidad = models.ForeignKey(Especialidad , null=True, on_delete=models.SET_NULL)
    idCita = models.ForeignKey(Cita, null=True, on_delete=models.SET_NULL,blank=True)
    fecha= models.DateField('FechaConsulta', blank=False, null=False)

    class Meta:
            verbose_name='Consulta'
            verbose_name_plural= 'Consultas'
            ordering=['idConsulta']
    
    def __str__(self):
        st = str(self.idConsulta) +' '+str(self.idPaciente)
        return st

class Incapacidad(models.Model):
    idIncapacidad = models.AutoField(primary_key=True)
    motivo = models.TextField('Motivo',max_length=400, blank=False, null=False)
    dias= models.IntegerField('Dias',blank=False, null=False)
    idConsulta = models.ForeignKey(Consulta, null= True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Incapacidad'
        verbose_name_plural = 'Incapacidades'
        ordering = ['idIncapacidad'] 

    def __str__(self):
        st = str(self.idConsulta) +' '+str(self.idIncapacidad)
        return st

apps/clinica/forms.py
from django import forms
from .models import *

""" Creacion de los formularios mediantes las funciones que 
    django nos proporciona para un manejo facil de la informacion
    utilizando las librerias forms al mismo tiempo podemos colocarles
    los label, widgets de los datos por lo cual algunas de las clases
    ser realizaron de esa manera"""

class ExpedienteForm(forms.ModelForm):
    class Meta:
        model = Expediente
        fields = '__all__'

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields ='__all__'

class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        fields ='__all__'

class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = '__all__'

        labels = {
            'idMedico' : 'Medico',
            'idPaciente' : 'Paciente',
            'idEspecialidad' : 'Especialidad',
            'idCita' : 'idCita',
            'fecha':'Fecha de Consulta',
            
        }

        widgets = {
            'idMedico': forms.Select(attrs={'class':'form-control'}),
            'idPaciente' : forms.Select(attrs={'class':'form-control'}),
            'idEspecialidad' : forms.Select(attrs={'class':'form-control'}),
            'idCita' : forms.Select(attrs={'class':'form-control'}),
            'fecha' : forms.DateInput(attrs={'class': 'datetime-input'}),
        }



class IncapacidadForm(forms.ModelForm):
    class Meta:
        model = Incapacidad
        fields = '__all__'

        labels = {
            'motivo' : 'Motivo',
            'dias' : 'Dias a autorizar',
            'idConsulta' : 'idConsulta',
        }

        widgets ={
            'motivo': forms.Textarea(attrs={'class':'form-control'}),
            'dias' : forms.TextInput(attrs={'class':'form-control'}),
            'idConsulta' : forms.Select(attrs={'class':'form-control'}),
        }

class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico
        fields ='__all__'

class EspecialidadForm(forms.ModelForm):
    class Meta:
        model = Especialidad
        fields = '__all__'

apps/clinica/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.

""" Creacion de las vistas con las que contara la aplicacion 
    las cuales estan clasificadas segun su CRUD al mismo tiempo
    se han importado las librerias necesarias para procesar el codigo
"""


class Inicio(TemplateView):
    template_name='index.html'

#CRUD ASIGNADO A PACIENTE
class ListadoExpediente(ListView):
    model = Expediente
    template_name='listado/listar_expediente.html'
    context_object_name='expedientes'
    queryset = Expediente.objects.all()
   
class ActualizarExpediente(UpdateView):
    model=Expediente
    template_name = 'modificables/editar_expediente.html'
    context_object_name='expedientes'
    form_class = ExpedienteForm
    success_url = reverse_lazy('clinica:listar_expediente')

class CrearExpediente(CreateView):
    model = Expediente
    form_class = ExpedienteForm
    template_name = 'clinica/crear_expediente.html'
    success_url = reverse_lazy('clinica:crear_paciente')

#CRUD ASIGNADO A PACIENTE
class ListadoPaciente(ListView):
    model = Paciente
    template_name='listado/listar_paciente.html'
    context_object_name='pacientes'
    queryset = Paciente.objects.all()
   
class ActualizarPaciente(UpdateView):
    model=Paciente
    template_name = 'modificables/editar_paciente.html'
    context_object_name='pacientes'
    form_class = PacienteForm
    success_url = reverse_lazy('clinica:listar_paciente')

class CrearPaciente(CreateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'clinica/crear_paciente.html'
    success_url = reverse_lazy('clinica:listar_paciente')


class EliminarPaciente(DeleteView):
    model = Paciente
    success_url = reverse_lazy('clinica:listar_paciente')

#CRUD ASIGNADO A CONSULTA

class ListadoConsulta(ListView):
    model = Consulta
    template_name='listado/listar_consulta.html'
    context_object_name='consultas'
    queryset = Consulta.objects.all()

class CrearConsulta(CreateView):
    model = Consulta
    form_class = ConsultaForm
    template_name = 'clinica/crear_consulta.html'
    success_url = reverse_lazy('clinica:listar_consulta')

class ActualizarConsulta(UpdateView):
    model=Consulta
    template_name = 'modificables/editar_consulta.html'
    context_object_name='consultas'
    form_class = ConsultaForm
    success_url = reverse_lazy('clinica:listar_consulta')

class EliminarConsulta(DeleteView):
    model = Consulta
    success_url = reverse_lazy('clinica:listar_consulta')

#CRUD ASIGNADO A CITA

class ListadoCita(ListView):
    model = Cita
    template_name='listado/listar_cita.html'
    context_object_name='citas'
    queryset=Cita.objects.all()

class CrearCita(CreateView):
    model = Cita
    form_class = CitaForm
    template_name = 'clinica/crear_cita.html'
    success_url = reverse_lazy('clinica:listar_cita')

class ActualizarCita(UpdateView):
    model = Cita
    template_name='modificables/editar_cita.html'
    context_object_name = 'citas'
    form_class = CitaForm
    success_url = reverse_lazy('clinica:listar_cita')

class EliminarCita(DeleteView):
    model = Cita
    success_url = reverse_lazy('clinica:listar_cita')

# CRUD ASIGNADOS A INCAPACIDAD

class ListadoIncapacidad(ListView):
    model = Incapacidad
    template_name = 'listado/listar_incapacidad.html'
    context_object_name='incapacidades'
    queryset = Incapacidad.objects.all()

class CrearIncapacidad(CreateView):
    model = Incapacidad
    form_class = IncapacidadForm
    template_name = 'clinica/crear_incapacidad.html'
    success_url = reverse_lazy('clinica:listar_incapacidad')

class EliminarIncapacidad(DeleteView):
    model = Incapacidad
    success_url = reverse_lazy('clinica:listar_incapacidad')


#CRUD ASIGNADO A MEDICOS

class ListadoMedicos(ListView):
    model = Medico
    template_name = 'listado/listar_medico.html'
    context_object_name = 'medicos'
    queryset = Medico.objects.all()

class CrearMedico(CreateView):
    model = Medico
    form_class = MedicoForm
    template_name = 'clinica/crear_medico.html'
    success_url = reverse_lazy('clinica:listar_medico')

class ActualizarMedico(UpdateView):
    model = Medico
    template_name='modificables/editar_medico.html'
    context_object_name = 'medicos'
    form_class = MedicoForm
    success_url = reverse_lazy('clinica:listar_medico')

class EliminarMedico(DeleteView):
    model = Medico
    success_url = reverse_lazy('clinica:listar_medico')


#CRUD ASIGNADO A ESPECIALIDADES

class ListadoEspecialidad(ListView):
    model = Especialidad
    template_name = 'listado/listar_especialidad.html'
    context_object_name = 'especialidades'
    queryset = Especialidad.objects.all()

class CrearEspecialidad(CreateView):
    model = Especialidad
    form_class = EspecialidadForm
    template_name='clinica/crear_especialidad.html'
    success_url = reverse_lazy('clinica:listar_especialidad')

class EliminarEspecialidad(DeleteView):
    model = Especialidad
    success_url = reverse_lazy('clinica:listar_especialidad')

templates/clinica/cita_confirm_delete.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}Eliminar Cita{% endblock %}
</head>
<body>
    {% block content %}
    <form method="POST">
        {% csrf_token %}
        <h1><p><strong>¿Desea eliminar el registro seleccionado: {{object}}?</strong></p></h1>
        <button type="submit">Confirmar</button>
    </form>
    {% endblock %}

    {% block footer %}
    <footer>
        <h1><center>°SISMEDICA°</center></h1>
    </footer>
    {% endblock %}
</body>
</html>

templates/clinica/consulta_confirm_delete.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}Eliminar Consulta{% endblock %}
</head>
<body>
    {% block content %}
    <form method="POST">
        {% csrf_token %}
        <h1><p><strong>¿Desea eliminar el registro seleccionado {{object}}?</strong></p></h1>
        <button type="submit">Confirmar</button>
    </form>
    {% endblock %}
    {% block footer %}
    <footer>
        <h1><center>°SISMEDICA°</center></h1>
    </footer>
    {% endblock %}
</body>
</html>

templates/clinica/crear_expediente.html
{% extends 'index.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}Crear Expediente Clinico{% endblock %}
    {% block extra %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
     <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script type="text/javascript" src="{% static 'js/formato.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/formato2.js' %}"> </script>
    {% endblock %}
</head>

<body>
    <hr>
    
    {% block content %}
    <div class="container">
    <h3>Ingresar Expediente</h3>
    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="" class="con">
                {% csrf_token %}
               
                <div class="row">
                    <div class="col-md-4 ">               
<p><label for="id_nombreCompleto">Nombres:</label> 
<input type="text" name="nombreCompleto" maxlength="200" id="id_nombreCompleto" class="form-control"></p>
</div>
<div class="col-md-4">
<p><label for="id_edad">Edad:</label> 
<input type="number" name="edad" id="id_edad" class="form-control"></p>
</div>
<div class="col-md-4">
<p><label for="id_sexo">Sexo:</label> 
<input type="text" name="sexo" maxlength="200" id="id_sexo" class="form-control"></p>
</div>
<div class="col-md-4 ">
<p><label for="id_estado">Estado:</label> 
<input type="text" name="estado" maxlength="200" id="id_estado" class="form-control"></p>
</div>
<div class="col-md-4">
    <p><label for="id_altura">Altura:</label> 
    <input type="number" name="altura" step="any" id="id_altura" class="form-control"></p>
    </div>
    <div class="col-md-4">
        <p><label for="id_peso">Peso:</label> 
        <input type="number" name="peso" step="any" id="id_peso" class="form-control"></p>
        </div>
</div>
<div class="row">
<div class="col-md-4">
<p><label for="id_temperatura">Temperatura:</label> 
<input type="number" name="temperatura" step="any" id="id_temperatura" class="form-control"></p>
</div>
<div class="col-md-4">
    <p><label for="id_presart">Presión Arterial:</label> 
    <input type="text" name="presart" maxlength="200" id="id_presart" class="form-control"></p>
    </div>
</div>
<div class="row">
<div class="col-md-4">
<p><label for="id_enfermedadeshe">Enfermedades Hereditarias:</label> 
<textarea name="enfermedadeshe" cols="40" rows="10" maxlength="400" id="id_enfermedadeshe" class="form-control"></textarea></p>
</div>
<div class="col-md-4">
<p><label for="id_alergias">Alergias:</label> 
<textarea name="alergias" cols="40" rows="10" maxlength="400" id="id_alergias" class="form-control"></textarea></p>
</div>
<div class="col-md-4">
<p><label for="id_obserpsi">Observaciones Psicologicas:</label> 
<textarea cols="40" rows="10" name="obserpsi" maxlength="200" id="id_obserpsi" class="form-control"></textarea></p>
</div>
</div>

                    <div class="float-right">
                        <button type="submit" class="btn btn-secondary">Crear</button>
                        <button type="reset" class="btn btn-secondary">Borrar</button>
                    </div>
            </form>
        </div>
    </div>
    
    {% endblock %}

</body>

{% block footer %}
    <footer>
        <h1><center>°SISMEDICA°</center></h1>
    </footer>
  
{% endblock footer %}
</body>
</html>

templates/clinica/crear_medico.html
{% extends 'index.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}Ingresar nuevo Paciente{% endblock %}
    {% block extra %}
   
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    
    <script type="text/javascript" src="{% static 'js/formato.js' %}"> </script>
    {% endblock %}
</head>
<body>

   

    <hr>
    {% block content %}
<div class="container">

    
    <h3 id="Ingreso">Ingresar los datos del Paciente</h3>
    <div class="row">
        <div class="col-md-12">
            <form action="" method="POST">
        
                {% csrf_token %}   
                
                {% if error %}
                    <h2>{{ error }}</h2>
                {% else %}    
                <div class="row">
                    <div class="col-md-4">
                        <label for="id_nombre">Nombre:</label><br/>
                        <input type="text" name="nombre" maxlength="150" required="" id="id_nombre" class="form-control">
                    </div>
                    <div class="col-md-4 ">
                        <label for="id_apellidos">Apellidos:</label><br/> 
                        <input type="text" name="apellidos" maxlength="100" required="" id="id_apellidos" class="form-control">
                    </div>
                </div>
                <div class="row">
                    
                    <div class="col-md-4 ">
                        <label for="id_dui">DUI:</label><br/>
                        <input type="text" name="dui" maxlength="10" required="" id="id_dui" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="id_sexo">Sexo:</label><br/>
                        <input type="text" name="sexo" maxlength="1" required="" id="id_sexo" class="form-control">
                    </div>
                    <div class="col-md-4 ">
                        <label for="id_email">Email:</label><br/>
                        <input type="text" name="email" maxlength="100" required="" id="id_email" class="form-control">
                    </div>
                </div>

                <div class="row">
                    
                    <div class="col-md-4 ">
                        <label for="id_estadoCivil">EstadoCivil:</label><br/>
                        <input type="text" name="estadoCivil" maxlength="10" required="" id="id_estadoCivil" class="form-control">
                        
                    </div>
                    <div class="col-md-4">
                        <label for="id_telefono">Telefono:</label><br/>
                        <input type="text" name="telefono" required="" id="id_telefono" class="form-control">
                    </div>
                    <div class="col-md-4 ">
                        <label for="id_fechaNaci">Fecha de Nacimiento:</label><br/>
                        <input type="date" name="fechaNaci" required="" id="id_fechaNaci" class="form-control">
                    </div>
                </div>
                   
                <div class="row">
                    
                    <div class="col-md-3 ">
                        <label for="id_departamento">Departamento:</label><br/>
                        <input type="text" name="departamento" maxlength="100" required="" id="id_departamento" class="form-control">
                    </div>
                    <div class="col-md-3">
                        <label for="id_municipio">Municipio:</label><br/> 
                        <input type="text" name="municipio" maxlength="100" required="" id="id_municipio" class="form-control">
                    </div>
                    <div class="col-md-3 ">
                        <label for="id_altura">Altura:</label><br/>
                        <input type="number" name="altura" required="" id="id_altura" class="form-control">
                    </div>
                    <div class="col-md-3 ">
                        <label for="id_peso">Peso:</label><br/>
                        <input type="number" name="peso" required="" id="id_peso" class="form-control">
                    </div>
                </div>
                   
                <div class="row">
                    
                    <div class="col-md-12">
                        <label for="id_direccion">Direccion:</label><br/> 
                        <textarea name="direccion" cols="40" rows="3" maxlength="300" required="" id="id_direccion" class="form-control"></textarea><br/>
                    </div>
                   
                </div>
                    
                <div class="float-right">
                    <input type="submit" class="btn btn-secondary" value="Guardar">
                    <input type="reset" class="btn btn-secondary" value="Cancelar">
                </div>
                
                {% endif %}
            </form>
        </div>
    </div>    
</div>
    {% endblock %}

    {% block footer %}
    <footer>
        <h1><center>°SISMEDICA°</center></h1>
    </footer>
    {% endblock %}
    
</body>
</html>